name: litroproject
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

